# Generated by Django 4.2.5 on 2023-10-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dg_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_session', models.CharField(unique=True)),
                ('platform', models.CharField(null=True)),
                ('app', models.CharField(null=True)),
                ('app_version', models.CharField(null=True)),
                ('request_headers', models.CharField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dg_user.usermodel')),
            ],
            options={
                'db_table': 'dg_auth',
                'ordering': ['-created_at'],
            },
        ),
    ]
