# Generated by Django 4.2.5 on 2023-10-19 16:08

import dg_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=dg_user.models.user_directory_path)),
                ('description', models.CharField(null=True)),
                ('link', models.CharField(null=True)),
                ('link_text', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dg_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
