# Generated by Django 4.2.5 on 2023-10-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
