# Generated by Django 4.2.5 on 2023-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_user', '0002_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
