# Generated by Django 4.2.5 on 2023-10-19 16:08

import dg_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField()),
                ('model_id', models.BigIntegerField()),
                ('path', models.ImageField(null=True, upload_to=dg_media.models.user_directory_path)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dg_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
