# Generated by Django 4.2.5 on 2023-10-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='format',
            field=models.SmallIntegerField(choices=[(0, '1_1'), (1, '4_5'), (2, '16_9')], default=0),
        ),
    ]
