# Generated by Django 4.2.5 on 2023-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'published'), (2, 'only_for_me')], default=1),
        ),
    ]
